Exception on /d8e37afe-b584-42df-919c-8257ad07ec40 [GET]
Traceback (most recent call last):
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/chasemcd/Library/Mobile Documents/com~apple~CloudDocs/Drive/GitHub/interactive-gym/server/server_app.py", line 245, in user_index
    return flask.render_template(
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/chasemcd/Library/Mobile Documents/com~apple~CloudDocs/Drive/GitHub/interactive-gym/server/server_app.py", line 245, in user_index
    return flask.render_template(
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/chasemcd/opt/anaconda3/envs/interactive-gym/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
